### ISSUE TITLE
xenserver-install-wizard failed to configure Management Interface

### ISSUE THREAD

**Issue by rushikeshjadhav** [xenserver/xenserver-install-wizard#59]
On a clean CentOS6.5 server 

[root@localhost buildroot]# xenserver-install-wizard 
/etc/init.d/message-switch: line 61: status_of_proc: command not found
/etc/init.d/forkexecd: line 59: status_of_proc: command not found
/etc/init.d/xcp-networkd: line 59: status_of_proc: command not found
/etc/init.d/xcp-rrdd: line 59: status_of_proc: command not found
/etc/init.d/ffs: line 69: status_of_proc: command not found
/etc/init.d/squeezed: line 59: status_of_proc: command not found
/etc/init.d/xapi: line 90: status_of_proc: command not found
logging: I recommend setting up rate-limiting
logging: I recommend enabling debug logging
OK: saved backup of /etc/rsyslog.conf in /etc/backup.rsyslog.conf
Shutting down system logger:                               [  OK  ]
Starting system logger:                                    [  OK  ]
Permanently stopping xend
Starting message switch: 
Starting forkexecd: 
Starting xcp-networkd: 
Starting xcp-rrdd: 
Starting ffs: 
Starting squeezed: 
Starting xapi: 
No bootloader to update, skipping
PIF scan OpaqueRef:3aaa1461-a93a-794e-1077-d38bb838d995
PIF.get_all_records
Setting ifcfg-eth0:NM_CONTROLLED to no
Setting ifcfg-eth0:ON_BOOT to no
Setting ifcfg-eth1:NM_CONTROLLED to no
Setting ifcfg-usb0:NM_CONTROLLED to no
Configuring usb0 with DHCP
Configuring eth1 with DHCP
Configuring eth0 as the management interface
Traceback (most recent call last):
  File "/usr/bin/xenserver-install-wizard", line 64, in <module>
    r = network.analyse(tui)
  File "/usr/share/xenserver-install-wizard/network.py", line 92, in analyse
    configure(config, new_interfaces)
  File "/usr/share/xenserver-install-wizard/network.py", line 73, in configure
    x.xenapi.host.management_reconfigure(config["device_to_pif"][config["management"]])
  File "/usr/lib/python2.6/site-packages/XenAPI.py", line 245, in **call**
    return self.__send(self.__name, args)
  File "/usr/lib/python2.6/site-packages/XenAPI.py", line 149, in xenapi_request
    result = _parse_result(getattr(self, methodname)(*full_params))
  File "/usr/lib/python2.6/site-packages/XenAPI.py", line 219, in _parse_result
    raise Failure(result['ErrorDescription'])
XenAPI.Failure: ['PIF_HAS_NO_NETWORK_CONFIGURATION']

**Comment by intechbgd** [comment]
HI @rushikeshjadhav , I just realized that in your case eth0 should be reconfigured as PIF device like:
xe pif-reconfigure-ip mode=static uuid=<eth0 PIF uuid xxxx.> IP=ipaddress netmask=255.255... and so on.
I think it is crucial to be set "mode=static" not to "mode=none"
You can get params by: xe pif-param-list uuid=<eth0 PIF uuid xxxx.....>
